# Generated by Django 3.2 on 2021-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nombre',
            field=models.CharField(default=2, max_length=200, verbose_name='Lugar'),
            preserve_default=False,
        ),
    ]
