# Generated by Django 3.2 on 2021-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del plan')),
                ('activo', models.CharField(choices=[('En proceso', 'En proceso'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado'), ('En Evaluación', 'En Evaluación'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=13, verbose_name='Estado del plan')),
            ],
            options={
                'verbose_name': 'Plan de contingencia',
                'verbose_name_plural': 'Planes de contingencia',
            },
        ),
    ]
