# Generated by Django 3.2 on 2021-05-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plandecontingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandecontingencia',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.area', verbose_name='área'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Desconocido', 'Desconocido'), ('En Evaluación', 'En Evaluación'), ('Finalizado', 'Finalizado'), ('En proceso', 'En proceso')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
