# Generated by Django 3.2 on 2021-05-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210501_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='altitud',
            field=models.CharField(default=1, max_length=20, verbose_name='Altitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='clave',
            field=models.CharField(default=1, max_length=10, verbose_name='Clave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='operando',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Operando'),
        ),
        migrations.AddField(
            model_name='area',
            name='ubicacion',
            field=models.CharField(default=1, max_length=255, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En proceso', 'En proceso'), ('En Evaluación', 'En Evaluación'), ('Iniciado', 'Iniciado'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
