# Generated by Django 3.2 on 2021-05-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210501_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSequia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.CharField(max_length=50, verbose_name='Intensidad de la sequía')),
                ('descripcion', models.TextField(max_length=5000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Monitor de sequía',
                'verbose_name_plural': 'Datos de la sequía',
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='operando',
            field=models.CharField(choices=[('No', 'No'), ('Sí', 'Sí')], default='No', max_length=2, verbose_name='Operando'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('Iniciado', 'Iniciado'), ('En proceso', 'En proceso'), ('Desconocido', 'Desconocido'), ('En Evaluación', 'En Evaluación')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
