# Generated by Django 3.2 on 2021-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210501_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nombre del análisis')),
                ('periodo', models.CharField(max_length=100, verbose_name='Periodo')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de fin')),
                ('fechaPaso', models.DateField(verbose_name='Fecha de paso')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo')),
                ('tipoAnalisis', models.CharField(max_length=100, verbose_name='Tipo de análisis')),
                ('comentario', models.CharField(max_length=255, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
            },
        ),
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Cultivo')),
                ('nombreCientifico', models.CharField(max_length=100, verbose_name='Nombre científico')),
                ('descripcion', models.TextField(max_length=5000, verbose_name='Descripcion')),
                ('mesDeSiembra', models.CharField(choices=[('Febrero', 'Febrero'), ('Enero', 'Enero')], default='Enero', max_length=30, verbose_name='Mes de siembra')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('En Evaluación', 'En Evaluación'), ('Finalizado', 'Finalizado'), ('Iniciado', 'Iniciado'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
