# Generated by Django 3.2 on 2021-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210505_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('En Evaluación', 'En Evaluación'), ('Desconocido', 'Desconocido'), ('Iniciado', 'Iniciado')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
