# Generated by Django 3.2 on 2021-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_plandecontingencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censotemperatura',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=26.0, max_digits=5, max_length=6, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('En Evaluación', 'En Evaluación'), ('Desconocido', 'Desconocido'), ('Finalizado', 'Finalizado'), ('Iniciado', 'Iniciado')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
