# Generated by Django 3.2 on 2021-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210505_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censotemperatura',
            options={'verbose_name': 'Temperatura', 'verbose_name_plural': 'Temperatura'},
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='mesDeSiembra',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero')], default='Enero', max_length=30, verbose_name='Mes de siembra'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En Evaluación', 'En Evaluación'), ('Iniciado', 'Iniciado'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
