# Generated by Django 3.2 on 2021-05-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210505_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='censotemperatura',
            name='Area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.area', verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='operando',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Operando'),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='mesDeSiembra',
            field=models.CharField(choices=[('Febrero', 'Febrero'), ('Enero', 'Enero')], default='Enero', max_length=30, verbose_name='Mes de siembra'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso'), ('En Evaluación', 'En Evaluación')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
