# Generated by Django 3.2 on 2021-05-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210505_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='censotemperatura',
            name='Cultivo',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cultivos', verbose_name='Cultivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En Evaluación', 'En Evaluación'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
