# Generated by Django 3.2 on 2021-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210505_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En Evaluación', 'En Evaluación'), ('Finalizado', 'Finalizado'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso'), ('Iniciado', 'Iniciado')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
