# Generated by Django 3.2 on 2021-05-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_plandecontingencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='operando',
            field=models.CharField(choices=[('No', 'No'), ('Sí', 'Sí')], default='No', max_length=2, verbose_name='Operando'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En Evaluación', 'En Evaluación'), ('Iniciado', 'Iniciado'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
