# Generated by Django 3.2 on 2021-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210505_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado'), ('Desconocido', 'Desconocido'), ('En Evaluación', 'En Evaluación')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
