# Generated by Django 3.2 on 2021-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_plandecontingencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='operando',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Operando'),
        ),
        migrations.AlterField(
            model_name='censotemperatura',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='censotemperatura',
            name='hora',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Desconocido', 'Desconocido'), ('En Evaluación', 'En Evaluación'), ('Finalizado', 'Finalizado'), ('Iniciado', 'Iniciado'), ('En proceso', 'En proceso')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
