# Generated by Django 3.2 on 2021-05-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210505_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivos',
            name='mesDeSiembra',
            field=models.CharField(choices=[('Agosto', 'Agosto'), ('Julio', 'Julio'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Noviembre', 'Noviembre'), ('Enero', 'Enero'), ('Diciembre', 'Diciembre'), ('Octubre', 'Octubre'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Septiembre', 'Septiembre')], default='Enero', max_length=30, verbose_name='Mes de siembra'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('En Evaluación', 'En Evaluación'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
